# Generated by Django 5.0.6 on 2024-06-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_daysweek_alter_allocation_days_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysweek',
            name='descricao',
        ),
    ]
