# Generated by Django 5.0.6 on 2024-06-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_daysweek_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='days_week',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, unique=True),
        ),
        migrations.DeleteModel(
            name='DaysWeek',
        ),
    ]
