# Generated by Django 5.0.6 on 2024-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_allocation_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='discipline_mode',
            field=models.BooleanField(default=False),
        ),
    ]
