# Generated by Django 5.0.6 on 2024-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discipline_discipline_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='timetable',
            field=models.CharField(choices=[('08:00', '08:00 - 10:00'), ('10:00', '10:00 - 12:00'), ('14:00', '14:00 - 16:00'), ('16:00', '16:00 - 18:00'), ('18:00', '18:00 - 20:00'), ('20:00', '20:00 - 22:00')], max_length=5, unique=True),
        ),
    ]
