# Generated by Django 5.0.6 on 2024-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_allocation_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='discipline_course',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
