# Generated by Django 5.0.6 on 2024-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_discipline_discipline_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='discipline_course',
            field=models.CharField(max_length=30),
        ),
    ]
