# Generated by Django 5.0.6 on 2024-07-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_discipline_discipline_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.physicalspace'),
        ),
    ]
